<a href="https://colab.research.google.com/github/NVHien10/BD_DQ/blob/Chau/DOTQUY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/SIC/data_dotquy.csv')
df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [ ]:
mask = df['gender'].isin(['Male', 'Female'])
df = df[mask]
print(df)

         id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes
1     51676  Female  61.0             0              0          Yes
2     31112    Male  80.0             0              1          Yes
3     60182  Female  49.0             0              0          Yes
4      1665  Female  79.0             1              0          Yes
...     ...     ...   ...           ...            ...          ...
5105  18234  Female  80.0             1              0          Yes
5106  44873  Female  81.0             0              0          Yes
5107  19723  Female  35.0             0              0          Yes
5108  37544    Male  51.0             0              0          Yes
5109  44679  Female  44.0             0              0          Yes

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked
1     Self-employed          Rural             202.21   NaN     never smoked
2           Private          Rural             105.92  32.5     never smoked
3           Private          Urban             171.23  34.4           smokes
4     Self-employed          Rural             174.12  24.0     never smoked
...             ...            ...                ...   ...              ...
5105        Private          Urban              83.75   NaN     never smoked
5106  Self-employed          Urban             125.20  40.0     never smoked
5107  Self-employed          Rural              82.99  30.6     never smoked
5108        Private          Rural             166.29  25.6  formerly smoked
5109       Govt_job          Urban              85.28  26.2          Unknown

      stroke
0          1
1          1
2          1
3          1
4          1
...      ...
5105       0
5106       0
5107       0
5108       0
5109       0

[5109 rows x 12 columns]

In [ ]:
df.loc[:, 'Residence_type'] = df['Residence_type'].replace({'Urban': 1, 'Rural': 0})
print(df)

         id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes
1     51676  Female  61.0             0              0          Yes
2     31112    Male  80.0             0              1          Yes
3     60182  Female  49.0             0              0          Yes
4      1665  Female  79.0             1              0          Yes
...     ...     ...   ...           ...            ...          ...
5105  18234  Female  80.0             1              0          Yes
5106  44873  Female  81.0             0              0          Yes
5107  19723  Female  35.0             0              0          Yes
5108  37544    Male  51.0             0              0          Yes
5109  44679  Female  44.0             0              0          Yes

          work_type  Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private               1             228.69  36.6  formerly smoked
1     Self-employed               0             202.21   NaN     never smoked
2           Private               0             105.92  32.5     never smoked
3           Private               1             171.23  34.4           smokes
4     Self-employed               0             174.12  24.0     never smoked
...             ...             ...                ...   ...              ...
5105        Private               1              83.75   NaN     never smoked
5106  Self-employed               1             125.20  40.0     never smoked
5107  Self-employed               0              82.99  30.6     never smoked
5108        Private               0             166.29  25.6  formerly smoked
5109       Govt_job               1              85.28  26.2          Unknown

      stroke
0          1
1          1
2          1
3          1
4          1
...      ...
5105       0
5106       0
5107       0
5108       0
5109       0

[5109 rows x 12 columns]

In [ ]:
df.loc[:, 'gender'] = df['gender'].replace({'Female': 1, 'Male': 0})
print(df)

         id gender   age  hypertension  heart_disease ever_married  work_type  \
0      9046      0  67.0             0              1          Yes          2
1     51676      1  61.0             0              0          Yes          3
2     31112      0  80.0             0              1          Yes          2
3     60182      1  49.0             0              0          Yes          2
4      1665      1  79.0             1              0          Yes          3
...     ...    ...   ...           ...            ...          ...        ...
5105  18234      1  80.0             1              0          Yes          2
5106  44873      1  81.0             0              0          Yes          3
5107  19723      1  35.0             0              0          Yes          3
5108  37544      0  51.0             0              0          Yes          2
5109  44679      1  44.0             0              0          Yes          0

      Residence_type  avg_glucose_level   bmi   smoking_status  stroke
0                  1             228.69  36.6  formerly smoked       1
1                  0             202.21   NaN     never smoked       1
2                  0             105.92  32.5     never smoked       1
3                  1             171.23  34.4           smokes       1
4                  0             174.12  24.0     never smoked       1
...              ...                ...   ...              ...     ...
5105               1              83.75   NaN     never smoked       0
5106               1             125.20  40.0     never smoked       0
5107               0              82.99  30.6     never smoked       0
5108               0             166.29  25.6  formerly smoked       0
5109               1              85.28  26.2          Unknown       0

[5109 rows x 12 columns]

In [ ]:
import numpy as np

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df.loc[:, 'work_type'] = le.fit_transform(df['work_type'])
print(df)

         id gender   age  hypertension  heart_disease ever_married  work_type  \
0      9046      0  67.0             0              1          Yes          2
1     51676      1  61.0             0              0          Yes          3
2     31112      0  80.0             0              1          Yes          2
3     60182      1  49.0             0              0          Yes          2
4      1665      1  79.0             1              0          Yes          3
...     ...    ...   ...           ...            ...          ...        ...
5105  18234      1  80.0             1              0          Yes          2
5106  44873      1  81.0             0              0          Yes          3
5107  19723      1  35.0             0              0          Yes          3
5108  37544      0  51.0             0              0          Yes          2
5109  44679      1  44.0             0              0          Yes          0

      Residence_type  avg_glucose_level   bmi   smoking_status  stroke
0                  1             228.69  36.6  formerly smoked       1
1                  0             202.21   NaN     never smoked       1
2                  0             105.92  32.5     never smoked       1
3                  1             171.23  34.4           smokes       1
4                  0             174.12  24.0     never smoked       1
...              ...                ...   ...              ...     ...
5105               1              83.75   NaN     never smoked       0
5106               1             125.20  40.0     never smoked       0
5107               0              82.99  30.6     never smoked       0
5108               0             166.29  25.6  formerly smoked       0
5109               1              85.28  26.2          Unknown       0

[5109 rows x 12 columns]

In [ ]:
from IPython.display import display
display(df)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,0,67.0,0,1,Yes,2,1,228.69,36.6,formerly smoked,1
1,51676,1,61.0,0,0,Yes,3,0,202.21,NaN,never smoked,1
2,31112,0,80.0,0,1,Yes,2,0,105.92,32.5,never smoked,1
3,60182,1,49.0,0,0,Yes,2,1,171.23,34.4,smokes,1
4,1665,1,79.0,1,0,Yes,3,0,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,1,80.0,1,0,Yes,2,1,83.75,NaN,never smoked,0
5106,44873,1,81.0,0,0,Yes,3,1,125.20,40.0,never smoked,0
5107,19723,1,35.0,0,0,Yes,3,0,82.99,30.6,never smoked,0
5108,37544,0,51.0,0,0,Yes,2,0,166.29,25.6,formerly smoked,0
5109,44679,1,44.0,0,0,Yes,0,1,85.28,26.2,Unknown,0